name: story_app1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_reaction_button: ^3.0.0+3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  lottie: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  timeago: ^3.7.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo_snap_story.png
    - assets/icon/like.png
    - assets/icon/love.png
    - assets/icon/care.png
    - assets/icon/haha.png
    - assets/icon/wow.png
    - assets/icon/like_default.png
    - assets/lottie/error_animation.json
    - assets/lottie/loading_animation.json
    - assets/lottie/white_loading_animation.json
