name: story_app1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  build_runner: ^2.4.15
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_reaction_button: ^3.0.0+3
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.0
  http: ^1.3.0
  image: ^4.5.3
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  location: ^8.0.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  timeago: ^3.7.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/like.png
    - assets/icon/love.png
    - assets/icon/care.png
    - assets/icon/haha.png
    - assets/icon/wow.png
    - assets/icon/like_default.png
    - assets/lottie/error_animation.json
    - assets/lottie/loading_animation.json
    - assets/lottie/white_loading_animation.json
    - assets/lottie/no_internet_animation.json
    - assets/img/image_not_found.png
